#!/usr/bin/env python3
"""BTC weekday edge signal bot.

Listens to Bybit 1h BTCUSDT klines, evaluates the completed-hour close against
the 1R weekday/Monday/regime statistics generated by the research scripts, sends
Telegram signals, and can optionally execute the setup on a separate Bybit Demo
Trading account with fixed USDT risk.
"""

from __future__ import annotations

import json
import logging
import math
import os
import queue
import signal
import threading
import time
import uuid
from collections import deque
from dataclasses import dataclass
from datetime import datetime, timezone
from html import escape
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import requests
from indicators import (
    ATR_LEN as NORMAL_ATR_LEN,
    ATR_PCTILE_WIN as NORMAL_ATR_PCTILE_WIN,
    FEATURE_NAMES,
    VOL_WIN as NORMAL_VOL_WIN,
    atr_pctile_last,
    extract_live_feature_vector,
    ind_atr,
    vol_ratio_last,
)
from pybit.unified_trading import HTTP, WebSocket


SYMBOL = os.environ.get("WEEKDAY_EDGE_SYMBOL", "BTCUSDT").strip().upper()
CATEGORY = os.environ.get("WEEKDAY_EDGE_CATEGORY", "linear").strip()
STRATEGY_NAME = os.environ.get("WEEKDAY_EDGE_STRATEGY_NAME", "weekday_1r_edge").strip() or "weekday_1r_edge"
PUBLIC_WS_DEMO = os.environ.get("WEEKDAY_EDGE_PUBLIC_WS_DEMO", os.environ.get("BYBIT_PUBLIC_WS_DEMO", "false")).lower() in {"1", "true", "yes"}
TRADING_DEMO = os.environ.get("WEEKDAY_EDGE_BYBIT_DEMO", "true").lower() in {"1", "true", "yes"}
TRADING_ENABLED = os.environ.get("WEEKDAY_EDGE_TRADING_ENABLED", "false").lower() in {"1", "true", "yes"}
API_KEY = os.environ.get("WEEKDAY_EDGE_BYBIT_API_KEY", "").strip()
API_SECRET = os.environ.get("WEEKDAY_EDGE_BYBIT_API_SECRET", "").strip()

TELEGRAM_BOT_TOKEN = os.environ.get("WEEKDAY_EDGE_TELEGRAM_BOT_TOKEN", os.environ.get("TELEGRAM_BOT_TOKEN", "")).strip()
TELEGRAM_CHAT_ID = os.environ.get(
    "WEEKDAY_EDGE_TELEGRAM_CHAT_ID",
    os.environ.get("TELEGRAM_ACCEPTED_SIGNALS_CHAT_ID", ""),
).strip()

LOG_DIR = Path(os.environ.get("WEEKDAY_EDGE_LOG_DIR", os.environ.get("LOG_DIR", "/app/logs")))
LEDGER_PATH = Path(os.environ.get("WEEKDAY_EDGE_LEDGER_PATH", str(LOG_DIR / "weekday_edge_signals.jsonl")))
STATS_PATH = Path(
    os.environ.get(
        "WEEKDAY_EDGE_STATS_PATH",
        "/app/weekday_1r_eval/btcusdt_20210525_20260525_1r_weekday_entry_hour_meaningful.csv",
    )
)

RISK_USDT = float(os.environ.get("WEEKDAY_EDGE_RISK_USDT", "100"))
ATR_LENGTH = int(os.environ.get("WEEKDAY_EDGE_ATR_LENGTH", "14"))
SL_ATR_MULTIPLE = float(os.environ.get("WEEKDAY_EDGE_SL_ATR_MULTIPLE", "2.0"))
RR = float(os.environ.get("WEEKDAY_EDGE_RR", "1.0"))
RL_PROBABILITY = float(os.environ.get("WEEKDAY_EDGE_RL_PROBABILITY", "0.55"))
RL_THRESHOLD = float(os.environ.get("WEEKDAY_EDGE_RL_THRESHOLD", "0.50"))
TAKER_FEE_RATE = float(os.environ.get("WEEKDAY_EDGE_TAKER_FEE_RATE", os.environ.get("TAKER_FEE_RATE", "0.00055")))
INCLUDE_FEES_IN_RISK = os.environ.get("WEEKDAY_EDGE_INCLUDE_FEES_IN_RISK", "true").lower() in {"1", "true", "yes"}
MAX_FEE_TO_PRICE_RISK = float(os.environ.get("WEEKDAY_EDGE_MAX_FEE_TO_PRICE_RISK", os.environ.get("MAX_FEE_TO_PRICE_RISK", "0.25")))
MIN_STOP_DISTANCE_PCT = float(os.environ.get("WEEKDAY_EDGE_MIN_STOP_DISTANCE_PCT", os.environ.get("MIN_STOP_DISTANCE_PCT", "0.001")))
ALLOW_MIN_QTY_OVERRISK = os.environ.get("WEEKDAY_EDGE_ALLOW_MIN_QTY_OVERRISK", "false").lower() in {"1", "true", "yes"}
ONE_POSITION_ONLY = os.environ.get("WEEKDAY_EDGE_ONE_POSITION_ONLY", "true").lower() in {"1", "true", "yes"}

MIN_TRADES = int(os.environ.get("WEEKDAY_EDGE_MIN_TRADES", "100"))
MIN_WEEKS = int(os.environ.get("WEEKDAY_EDGE_MIN_WEEKS", "40"))
MIN_CI_LOW = float(os.environ.get("WEEKDAY_EDGE_MIN_AVG_R_CI_LOW", "0.0"))
REQUIRE_FDR = os.environ.get("WEEKDAY_EDGE_REQUIRE_FDR", "false").lower() in {"1", "true", "yes"}
MAX_Q_VALUE = float(os.environ.get("WEEKDAY_EDGE_MAX_Q_VALUE", "0.10"))
FAMILY_ALLOWLIST = {
    item.strip()
    for item in os.environ.get("WEEKDAY_EDGE_CONTEXT_FAMILIES", "").split(",")
    if item.strip()
}
MAX_MATCHES_IN_MESSAGE = int(os.environ.get("WEEKDAY_EDGE_MAX_MATCHES_IN_MESSAGE", "5"))
WS_STALE_SECONDS = int(os.environ.get("WEEKDAY_EDGE_WS_STALE_SECONDS", os.environ.get("WS_STALE_SECONDS", "900")))
HEARTBEAT_SECONDS = int(os.environ.get("WEEKDAY_EDGE_HEARTBEAT_SECONDS", "3600"))
RL_EXECUTION_URL = os.environ.get("WEEKDAY_EDGE_RL_EXECUTION_URL", os.environ.get("RL_EXECUTION_URL", "")).strip()
RL_EXECUTION_TIMEOUT_SECONDS = float(
    os.environ.get(
        "WEEKDAY_EDGE_RL_EXECUTION_TIMEOUT_SECONDS",
        os.environ.get("RL_EXECUTION_TIMEOUT_SECONDS", "1.0"),
    )
)
RL_EXECUTION_QUEUE_SIZE = int(
    os.environ.get(
        "WEEKDAY_EDGE_RL_EXECUTION_QUEUE_SIZE",
        os.environ.get("RL_EXECUTION_QUEUE_SIZE", "1000"),
    )
)

HOURLY_WARMUP_BARS = int(os.environ.get("WEEKDAY_EDGE_HOURLY_WARMUP_BARS", "1200"))
DAILY_WARMUP_BARS = int(os.environ.get("WEEKDAY_EDGE_DAILY_WARMUP_BARS", "700"))


LOG_DIR.mkdir(parents=True, exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)sZ [%(levelname)-5s] [weekday-edge] %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler(LOG_DIR / "weekday_edge_bot.log"),
    ],
)
log = logging.getLogger("weekday_edge")


WEEKDAY_NAME = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]


DEFAULT_RULES: list[dict[str, Any]] = [
    {
        "context_source": "after_monday_close",
        "context_family": "monday_high_low_sequence",
        "context_value": "high_first",
        "entry_weekday": "Tuesday",
        "entry_hour_utc": 20,
        "direction": "long",
        "trades": 116,
        "weeks": 116,
        "win_rate": 0.6121,
        "avg_r": 0.2241,
        "avg_r_ci_low": 0.0345,
        "q_value_bh": 1.0,
    },
    {
        "context_source": "after_monday_close",
        "context_family": "monday_close_vs_pwh_pwl",
        "context_value": "inside_previous_week_range",
        "entry_weekday": "Wednesday",
        "entry_hour_utc": 0,
        "direction": "long",
        "trades": 194,
        "weeks": 194,
        "win_rate": 0.5722,
        "avg_r": 0.1443,
        "avg_r_ci_low": 0.0103,
        "q_value_bh": 0.9975,
    },
    {
        "context_source": "after_monday_close",
        "context_family": "entry_vs_monday_mid",
        "context_value": "above_or_at_monday_mid",
        "entry_weekday": "Thursday",
        "entry_hour_utc": 5,
        "direction": "short",
        "trades": 141,
        "weeks": 141,
        "win_rate": 0.5957,
        "avg_r": 0.1915,
        "avg_r_ci_low": 0.0355,
        "q_value_bh": 0.9980,
    },
    {
        "context_source": "after_monday_close",
        "context_family": "entry_vs_monday_open",
        "context_value": "above_or_at_monday_open",
        "entry_weekday": "Friday",
        "entry_hour_utc": 18,
        "direction": "long",
        "trades": 127,
        "weeks": 127,
        "win_rate": 0.6142,
        "avg_r": 0.2283,
        "avg_r_ci_low": 0.0551,
        "q_value_bh": 0.9975,
    },
    {
        "context_source": "after_monday_close",
        "context_family": "monday_color",
        "context_value": "red",
        "entry_weekday": "Saturday",
        "entry_hour_utc": 10,
        "direction": "long",
        "trades": 124,
        "weeks": 124,
        "win_rate": 0.6210,
        "avg_r": 0.2419,
        "avg_r_ci_low": 0.0645,
        "q_value_bh": 0.7196,
    },
    {
        "context_source": "after_monday_close",
        "context_family": "entry_vs_monday_mid",
        "context_value": "below_monday_mid",
        "entry_weekday": "Sunday",
        "entry_hour_utc": 21,
        "direction": "short",
        "trades": 125,
        "weeks": 125,
        "win_rate": 0.6240,
        "avg_r": 0.2480,
        "avg_r_ci_low": 0.0880,
        "q_value_bh": 0.9980,
    },
    {
        "context_source": "all_weekdays",
        "context_family": "daily_regime",
        "context_value": "chop",
        "entry_weekday": "Saturday",
        "entry_hour_utc": 12,
        "direction": "long",
        "trades": 136,
        "weeks": 136,
        "win_rate": 0.5956,
        "avg_r": 0.1912,
        "avg_r_ci_low": 0.0294,
        "q_value_bh": 0.9961,
    },
    {
        "context_source": "after_monday_close",
        "context_family": "monday_close_vs_pwh_pwl_x_daily_regime",
        "context_value": "inside_previous_week_range|chop",
        "entry_weekday": "Saturday",
        "entry_hour_utc": 12,
        "direction": "long",
        "trades": 103,
        "weeks": 103,
        "win_rate": 0.6117,
        "avg_r": 0.2233,
        "avg_r_ci_low": 0.0291,
        "q_value_bh": 1.0,
    },
]


@dataclass(frozen=True)
class Rule:
    context_source: str
    context_family: str
    context_value: str
    entry_weekday: str
    entry_weekday_num: int
    entry_hour_utc: int
    direction: str
    trades: int
    weeks: int
    win_rate: float
    avg_r: float
    avg_r_ci_low: float
    avg_r_ci_high: float | None
    q_value_bh: float | None

    @property
    def score(self) -> tuple[float, float, int]:
        return (self.avg_r_ci_low, self.avg_r, self.trades)

    @property
    def label(self) -> str:
        return f"{self.context_family}={self.context_value}"


def parse_chat_target(raw: str) -> tuple[str, int | None]:
    text = str(raw or "").strip()
    if not text:
        return "", None
    for separator in ("_", ":"):
        head, sep, tail = text.rpartition(separator)
        if sep and head and tail.isdigit():
            return head, int(tail)
    return text, None


def to_float(value: Any, default: float = float("nan")) -> float:
    try:
        return float(str(value))
    except Exception:
        return default


def finite_float(value: Any) -> float | None:
    try:
        out = float(value)
    except (TypeError, ValueError):
        return None
    return out if math.isfinite(out) else None


def utc_ts(value: Any) -> pd.Timestamp:
    ts = pd.Timestamp(value)
    if ts.tzinfo is None:
        return ts.tz_localize("UTC")
    return ts.tz_convert("UTC")


def fmt(value: float, digits: int = 2) -> str:
    if not np.isfinite(value):
        return "-"
    return f"{value:.{digits}f}"


def fmt_price(value: float) -> str:
    if not np.isfinite(value):
        return "-"
    if abs(value) >= 100:
        return f"{value:.2f}"
    if abs(value) >= 1:
        return f"{value:.4f}"
    return f"{value:.8f}".rstrip("0").rstrip(".")


def round_to_step(value: float, step: float) -> float:
    if step <= 0:
        return float(value)
    precision = max(0, int(round(-math.log10(step))))
    return round(round(float(value) / step) * step, precision)


def floor_to_step(value: float, step: float) -> float:
    if step <= 0:
        return float(value)
    precision = max(0, int(round(-math.log10(step))))
    return round(math.floor(float(value) / step) * step, precision)


def qty_to_str(value: float, step: float = 0.0) -> str:
    if step > 0:
        precision = max(0, int(round(-math.log10(step))))
        return f"{value:.{precision}f}"
    return f"{round(value, 8):.8f}".rstrip("0").rstrip(".") or "0"


def jsonable(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(key): jsonable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [jsonable(item) for item in value]
    if isinstance(value, pd.Timestamp):
        return value.isoformat()
    if isinstance(value, datetime):
        return value.astimezone(timezone.utc).isoformat() if value.tzinfo else value.replace(tzinfo=timezone.utc).isoformat()
    if isinstance(value, np.generic):
        return jsonable(value.item())
    if isinstance(value, float) and not math.isfinite(value):
        return None
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return str(value)


class TelegramNotifier:
    def __init__(self, token: str, chat_id: str) -> None:
        self.token = token
        self.chat_id, self.thread_id = parse_chat_target(chat_id)
        self.enabled = bool(self.token and self.chat_id)

    def send(self, lines: list[str]) -> None:
        if not self.enabled:
            return
        payload: dict[str, Any] = {
            "chat_id": self.chat_id,
            "text": "\n".join(lines),
            "parse_mode": "HTML",
            "disable_web_page_preview": True,
        }
        if self.thread_id is not None:
            payload["message_thread_id"] = self.thread_id
        try:
            resp = requests.post(
                f"https://api.telegram.org/bot{self.token}/sendMessage",
                json=payload,
                timeout=10,
            )
            if resp.status_code >= 400:
                log.warning("Telegram send failed status=%s: %s", resp.status_code, resp.text[:200].replace(self.token, "<redacted>"))
        except Exception as exc:
            log.warning("Telegram send failed: %s", str(exc).replace(self.token, "<redacted>"))


class RlSidecarClient:
    def __init__(self, url: str, timeout_seconds: float, queue_size: int) -> None:
        self.url = url
        self.timeout = max(0.1, timeout_seconds)
        self.queue: queue.Queue[dict[str, Any]] | None = None
        self.thread: threading.Thread | None = None
        if self.url:
            self.queue = queue.Queue(maxsize=max(1, queue_size))
            self.thread = threading.Thread(target=self._worker, name="weekday-edge-rl-dispatch", daemon=True)
            self.thread.start()
            log.info("RL execution sidecar enabled url=%s", self.url)
        else:
            log.info("RL execution sidecar disabled; RL_EXECUTION_URL is empty")

    def enqueue(self, payload: dict[str, Any]) -> dict[str, Any]:
        if not self.url or self.queue is None:
            return {"enabled": False, "queued": False, "message": "RL execution URL is empty"}
        clean = jsonable(payload)
        try:
            self.queue.put_nowait(clean)
            return {"enabled": True, "queued": True}
        except queue.Full:
            log.warning(
                "[rl] Dispatch queue full; dropping %s %s %s",
                payload.get("status"),
                payload.get("symbol"),
                payload.get("strategy"),
            )
            return {"enabled": True, "queued": False, "message": "RL dispatch queue full"}

    def _worker(self) -> None:
        assert self.queue is not None
        while True:
            payload = self.queue.get()
            try:
                response = requests.post(self.url, json=payload, timeout=self.timeout)
                if response.status_code >= 300:
                    log.warning("[rl] Sidecar returned HTTP %s: %s", response.status_code, response.text[:300])
                else:
                    log.info(
                        "[rl] Dispatched %s %s %s",
                        payload.get("status"),
                        payload.get("symbol"),
                        payload.get("strategy"),
                    )
            except Exception as exc:
                log.warning("[rl] Signal dispatch failed: %s", exc)
            finally:
                self.queue.task_done()


class NormalRlContextBuilder:
    """Build the same market-context envelope the RL sidecar receives from mm-bot."""

    def __init__(self, http: HTTP) -> None:
        self.http = http
        self.oi_history: dict[str, deque[dict[str, Any]]] = {}
        self.funding_history: dict[str, deque[dict[str, Any]]] = {}
        self.instrument_cache: dict[str, dict[str, Any]] = {}

    @staticmethod
    def _extract_response_list(resp: dict[str, Any]) -> list[dict[str, Any]]:
        items = resp.get("result", {}).get("list", []) if isinstance(resp, dict) else []
        return [item for item in items if isinstance(item, dict)] if isinstance(items, list) else []

    @staticmethod
    def _zscore(value: float | None, history_values: list[float]) -> float | None:
        if value is None or len(history_values) < 5:
            return None
        arr = np.asarray(history_values, dtype=np.float64)
        std = float(np.std(arr))
        if arr.size < 5 or std <= 0 or not math.isfinite(std):
            return None
        out = (value - float(np.mean(arr))) / std
        return float(out) if math.isfinite(out) else None

    def instrument_info(self, symbol: str) -> dict[str, Any]:
        if symbol not in self.instrument_cache:
            response = self.http.get_instruments_info(category=CATEGORY, symbol=symbol)
            items = self._extract_response_list(response)
            if not items:
                self.instrument_cache[symbol] = {}
            else:
                item = items[0]
                lot = item.get("lotSizeFilter", {})
                price = item.get("priceFilter", {})
                leverage = item.get("leverageFilter", {})
                self.instrument_cache[symbol] = {
                    "qty_step": finite_float(lot.get("qtyStep")) or 0.0,
                    "min_qty": finite_float(lot.get("minOrderQty")) or 0.0,
                    "tick_size": finite_float(price.get("tickSize")) or 0.0,
                    "min_leverage": leverage.get("minLeverage"),
                    "max_leverage": leverage.get("maxLeverage"),
                    "leverage_step": leverage.get("leverageStep"),
                    "status": item.get("status"),
                }
        return dict(self.instrument_cache[symbol])

    def market_snapshot(self, symbol: str) -> dict[str, Any]:
        try:
            response = self.http.get_tickers(category=CATEGORY, symbol=symbol)
            items = self._extract_response_list(response)
            return dict(items[0]) if items else {}
        except Exception as exc:
            log.debug("[%s] market snapshot fetch failed: %s", symbol, exc)
            return {}

    @staticmethod
    def normal_feature_snapshot(hourly: pd.DataFrame, direction: str) -> dict[str, float]:
        if hourly.empty:
            return {}
        bars: list[dict[str, float]] = []
        for row in hourly.sort_values("open_time").tail(max(260, NORMAL_ATR_PCTILE_WIN + 160)).itertuples(index=False):
            ts = int(utc_ts(getattr(row, "open_time")).timestamp() * 1000)
            bars.append(
                {
                    "ts": ts,
                    "open": float(getattr(row, "open")),
                    "high": float(getattr(row, "high")),
                    "low": float(getattr(row, "low")),
                    "close": float(getattr(row, "close")),
                    "volume": float(getattr(row, "volume")),
                }
            )
        vector = extract_live_feature_vector(bars, direction.lower() == "long")
        if vector is None:
            return {}
        return {name: float(value) for name, value in zip(FEATURE_NAMES, vector)}

    @staticmethod
    def regime_context(hourly: pd.DataFrame, entry_time: pd.Timestamp, daily_regime: str | None) -> dict[str, Any]:
        out: dict[str, Any] = {
            "session_tag": "unspecified",
            "minutes_to_session_open": None,
            "minutes_to_session_close": None,
            "atr": None,
            "atr_pctile": None,
            "volume_ratio": None,
            "realized_vol_20": None,
            "realized_vol_96": None,
            "volume_percentile_200": None,
            "daily_regime": daily_regime,
            "timeframe": "1h",
        }
        frame = hourly.sort_values("open_time").reset_index(drop=True)
        if len(frame) < max(NORMAL_ATR_LEN + 5, NORMAL_VOL_WIN + 5, NORMAL_ATR_PCTILE_WIN + 5):
            return out
        try:
            close = frame["close"].to_numpy(np.float64)
            high = frame["high"].to_numpy(np.float64)
            low = frame["low"].to_numpy(np.float64)
            volume = frame["volume"].to_numpy(np.float64)
            atr = ind_atr(high, low, close, NORMAL_ATR_LEN)
            atr_last = float(atr[-1]) if len(atr) else float("nan")
            atr_pctile = atr_pctile_last(atr, NORMAL_ATR_PCTILE_WIN)
            vol_ratio = vol_ratio_last(volume, NORMAL_VOL_WIN)
            rets = np.diff(np.log(np.maximum(close, 1e-12)))
            rv_20 = float(np.std(rets[-20:])) if len(rets) >= 20 else float("nan")
            rv_96 = float(np.std(rets[-96:])) if len(rets) >= 96 else float("nan")
            vol_window = volume[-200:] if len(volume) >= 200 else volume
            vol_pct = float(np.mean(vol_window <= volume[-1])) if len(vol_window) else float("nan")
            out.update(
                {
                    "atr": atr_last if math.isfinite(atr_last) else None,
                    "atr_pctile": atr_pctile if math.isfinite(atr_pctile) else None,
                    "volume_ratio": vol_ratio if math.isfinite(vol_ratio) else None,
                    "realized_vol_20": rv_20 if math.isfinite(rv_20) else None,
                    "realized_vol_96": rv_96 if math.isfinite(rv_96) else None,
                    "volume_percentile_200": vol_pct if math.isfinite(vol_pct) else None,
                    "entry_hour_utc": int(entry_time.hour),
                    "entry_weekday_num": int(entry_time.weekday()),
                }
            )
        except Exception as exc:
            log.debug("[%s] regime context build failed: %s", SYMBOL, exc)
        return out

    def build(self, signal_data: dict[str, Any], hourly: pd.DataFrame, contexts: dict[str, str]) -> dict[str, Any]:
        symbol = str(signal_data.get("symbol") or SYMBOL).upper()
        local_dt = datetime.now(timezone.utc)
        entry = finite_float(signal_data.get("entry"))
        stop = finite_float(signal_data.get("stop"))
        target = finite_float(signal_data.get("target"))
        ticker = self.market_snapshot(symbol)
        instrument = self.instrument_info(symbol)
        context: dict[str, Any] = {
            "captured_at_utc": local_dt.isoformat(),
            "captured_at_ms": int(local_dt.timestamp() * 1000),
            "symbol": symbol,
            "strategy": STRATEGY_NAME,
            "direction": signal_data.get("direction"),
            "ticker": ticker,
            "basis": {"mark_price": None, "index_price": None, "basis_pct": None},
            "orderbook": {
                "best_bid": None,
                "best_ask": None,
                "spread": None,
                "spread_bps": None,
                "bid_notional_top10": None,
                "ask_notional_top10": None,
                "imbalance_top10": None,
                "raw": None,
            },
            "trade_flow_60s": {
                "trade_count": None,
                "buy_notional": None,
                "sell_notional": None,
                "buy_qty": None,
                "sell_qty": None,
                "notional_imbalance": None,
                "raw": None,
            },
            "open_interest": {
                "current": None,
                "delta_5m": None,
                "delta_15m": None,
                "delta_1h": None,
                "zscore": None,
                "history": [],
            },
            "funding": {
                "current": None,
                "next_funding_time_ms": None,
                "minutes_to_next_funding": None,
                "zscore": None,
                "history": [],
            },
        }
        try:
            response = self.http.get_server_time()
            context["server_time"] = response.get("result") if isinstance(response, dict) else None
        except Exception as exc:
            log.debug("[%s] server time fetch failed: %s", symbol, exc)

        mark = finite_float(ticker.get("markPrice")) if ticker else None
        index = finite_float(ticker.get("indexPrice")) if ticker else None
        basis_pct = ((mark - index) / index) if (mark is not None and index not in (None, 0.0)) else None
        context["basis"] = {
            "mark_price": mark,
            "index_price": index,
            "basis_pct": basis_pct if basis_pct is None or math.isfinite(basis_pct) else None,
        }

        try:
            response = self.http.get_orderbook(category=CATEGORY, symbol=symbol, limit=50)
            orderbook = response.get("result", {}) if isinstance(response, dict) else {}
            bids = [item for item in orderbook.get("b", []) if isinstance(item, (list, tuple)) and len(item) >= 2]
            asks = [item for item in orderbook.get("a", []) if isinstance(item, (list, tuple)) and len(item) >= 2]
            best_bid = finite_float(bids[0][0]) if bids else None
            best_ask = finite_float(asks[0][0]) if asks else None
            spread = (best_ask - best_bid) if (best_ask is not None and best_bid is not None) else None
            mid = ((best_ask + best_bid) / 2.0) if (best_ask is not None and best_bid is not None) else None
            spread_bps = (spread / mid * 1e4) if (spread is not None and mid not in (None, 0.0)) else None
            bid_notional = 0.0
            ask_notional = 0.0
            for item in bids[:10]:
                price = finite_float(item[0])
                qty = finite_float(item[1])
                if price is not None and qty is not None:
                    bid_notional += price * qty
            for item in asks[:10]:
                price = finite_float(item[0])
                qty = finite_float(item[1])
                if price is not None and qty is not None:
                    ask_notional += price * qty
            denom = bid_notional + ask_notional
            context["orderbook"] = {
                "best_bid": best_bid,
                "best_ask": best_ask,
                "spread": spread,
                "spread_bps": spread_bps,
                "bid_notional_top10": bid_notional,
                "ask_notional_top10": ask_notional,
                "imbalance_top10": ((bid_notional - ask_notional) / denom) if denom > 0 else None,
                "raw": orderbook,
            }
        except Exception as exc:
            log.debug("[%s] orderbook fetch failed: %s", symbol, exc)

        try:
            response = self.http.get_public_trade_history(category=CATEGORY, symbol=symbol, limit=200)
            trades = self._extract_response_list(response)
            now_ms = int(local_dt.timestamp() * 1000)
            buy_notional = sell_notional = buy_qty = sell_qty = 0.0
            count = 0
            for trade in trades:
                ts = int(finite_float(trade.get("time")) or finite_float(trade.get("T")) or 0)
                if ts <= 0 or now_ms - ts > 60_000:
                    continue
                price = finite_float(trade.get("price") or trade.get("p"))
                qty = finite_float(trade.get("size") or trade.get("v"))
                if price is None or qty is None:
                    continue
                count += 1
                if str(trade.get("side", "")).lower() == "buy":
                    buy_notional += price * qty
                    buy_qty += qty
                elif str(trade.get("side", "")).lower() == "sell":
                    sell_notional += price * qty
                    sell_qty += qty
            denom = buy_notional + sell_notional
            context["trade_flow_60s"] = {
                "trade_count": count,
                "buy_notional": buy_notional,
                "sell_notional": sell_notional,
                "buy_qty": buy_qty,
                "sell_qty": sell_qty,
                "notional_imbalance": ((buy_notional - sell_notional) / denom) if denom > 0 else None,
                "raw": trades[:100],
            }
        except Exception as exc:
            log.debug("[%s] public trade history fetch failed: %s", symbol, exc)

        oi_current = finite_float(ticker.get("openInterest")) if ticker else None
        oi_rows: list[dict[str, Any]] = []
        try:
            response = self.http.get_open_interest(category=CATEGORY, symbol=symbol, intervalTime="5min", limit=24)
            for row in self._extract_response_list(response):
                ts = int(finite_float(row.get("timestamp")) or 0)
                value = finite_float(row.get("openInterest"))
                if ts > 0 and value is not None:
                    oi_rows.append({"ts": ts, "open_interest": value})
            oi_rows.sort(key=lambda item: item["ts"])
        except Exception as exc:
            log.debug("[%s] open interest history fetch failed: %s", symbol, exc)
        if oi_current is None and oi_rows:
            oi_current = finite_float(oi_rows[-1].get("open_interest"))
        history = self.oi_history.setdefault(symbol, deque(maxlen=512))
        for row in oi_rows:
            if not history or history[-1].get("ts") != row.get("ts"):
                history.append(row)
        oi_values = [value for value in (finite_float(item.get("open_interest")) for item in history) if value is not None]
        context["open_interest"] = {
            "current": oi_current,
            "delta_5m": oi_current - oi_values[-2] if oi_current is not None and len(oi_values) >= 2 else None,
            "delta_15m": oi_current - oi_values[-4] if oi_current is not None and len(oi_values) >= 4 else None,
            "delta_1h": oi_current - oi_values[-13] if oi_current is not None and len(oi_values) >= 13 else None,
            "zscore": self._zscore(oi_current, oi_values[-100:]),
            "history": list(history)[-120:],
        }

        funding_current = finite_float(ticker.get("fundingRate")) if ticker else None
        funding_rows: list[dict[str, Any]] = []
        try:
            response = self.http.get_funding_rate_history(category=CATEGORY, symbol=symbol, limit=50)
            for row in self._extract_response_list(response):
                ts = int(finite_float(row.get("fundingRateTimestamp")) or finite_float(row.get("fundingRateTs")) or 0)
                value = finite_float(row.get("fundingRate"))
                if ts > 0 and value is not None:
                    funding_rows.append({"ts": ts, "funding_rate": value})
            funding_rows.sort(key=lambda item: item["ts"])
        except Exception as exc:
            log.debug("[%s] funding history fetch failed: %s", symbol, exc)
        funding_history = self.funding_history.setdefault(symbol, deque(maxlen=512))
        for row in funding_rows:
            if not funding_history or funding_history[-1].get("ts") != row.get("ts"):
                funding_history.append(row)
        funding_values = [value for value in (finite_float(item.get("funding_rate")) for item in funding_history) if value is not None]
        if funding_current is None and funding_values:
            funding_current = funding_values[-1]
        next_funding_ms = int(finite_float(ticker.get("nextFundingTime")) or 0) if ticker else 0
        context["funding"] = {
            "current": funding_current,
            "next_funding_time_ms": next_funding_ms if next_funding_ms > 0 else None,
            "minutes_to_next_funding": ((next_funding_ms - int(local_dt.timestamp() * 1000)) / 60000.0) if next_funding_ms > 0 else None,
            "zscore": self._zscore(funding_current, funding_values[-100:]),
            "history": list(funding_history)[-120:],
        }

        entry_time = utc_ts(signal_data.get("entry_time"))
        context["regime"] = self.regime_context(hourly, entry_time, contexts.get("daily_regime"))
        tick = finite_float(instrument.get("tick_size"))
        stop_ticks = abs(entry - stop) / tick if entry is not None and stop is not None and tick and tick > 0 else None
        target_ticks = abs(target - entry) / tick if entry is not None and target is not None and tick and tick > 0 else None
        context["execution_plan"] = {
            "expected_entry": entry,
            "expected_stop": stop,
            "expected_target": target,
            "trail_dist": None,
            "tick_size": instrument.get("tick_size"),
            "stop_distance_ticks": stop_ticks,
            "target_distance_ticks": target_ticks,
            "qty_step": instrument.get("qty_step"),
            "min_qty": instrument.get("min_qty"),
        }
        context["instrument_constraints"] = {
            "qty_step": instrument.get("qty_step"),
            "min_qty": instrument.get("min_qty"),
            "tick_size": instrument.get("tick_size"),
            "min_leverage": instrument.get("min_leverage"),
            "max_leverage": instrument.get("max_leverage"),
            "leverage_step": instrument.get("leverage_step"),
        }
        context["weekday_edge"] = {
            "contexts": contexts,
            "rule": signal_data.get("rule"),
            "matched_rules": signal_data.get("matched_rules"),
            "research_window": "2021-05-25..2026-05-25",
            "no_lookahead": "daily regimes and Monday context use completed candles only",
        }
        context["provenance"] = {
            "bot_version": "weekday-edge-1",
            "strategy": STRATEGY_NAME,
            "symbol": symbol,
            "timeframe": "1h",
            "feature_schema": list(FEATURE_NAMES),
            "runtime": {
                "public_ws_demo": PUBLIC_WS_DEMO,
                "bybit_demo": TRADING_DEMO,
            },
            "build": {
                "git_commit": os.environ.get("GIT_COMMIT") or os.environ.get("COMMIT_SHA"),
                "image_tag": os.environ.get("IMAGE_TAG") or os.environ.get("DOCKER_IMAGE_TAG"),
            },
        }
        return context


def load_rules(path: Path) -> list[Rule]:
    if path.exists():
        frame = pd.read_csv(path)
        log.info("Loaded weekday edge statistics from %s (%d rows)", path, len(frame))
    else:
        frame = pd.DataFrame(DEFAULT_RULES)
        log.warning("Stats file %s not found; using %d built-in fallback rules", path, len(frame))

    if "entry_weekday_num" not in frame.columns:
        frame["entry_weekday_num"] = frame["entry_weekday"].map({name: i for i, name in enumerate(WEEKDAY_NAME)})
    if "context_source" not in frame.columns:
        frame["context_source"] = "after_monday_close"
    if "avg_r_ci_high" not in frame.columns:
        frame["avg_r_ci_high"] = np.nan
    if "q_value_bh" not in frame.columns:
        frame["q_value_bh"] = np.nan

    frame = frame[
        (frame["trades"].astype(float) >= MIN_TRADES)
        & (frame["weeks"].astype(float) >= MIN_WEEKS)
        & (frame["avg_r_ci_low"].astype(float) >= MIN_CI_LOW)
    ].copy()
    if FAMILY_ALLOWLIST:
        frame = frame[frame["context_family"].isin(FAMILY_ALLOWLIST)].copy()
    if REQUIRE_FDR:
        frame = frame[pd.to_numeric(frame["q_value_bh"], errors="coerce").fillna(1.0) <= MAX_Q_VALUE].copy()

    rules: list[Rule] = []
    for row in frame.to_dict(orient="records"):
        direction = str(row.get("direction", "")).lower()
        if direction not in {"long", "short"}:
            continue
        rules.append(
            Rule(
                context_source=str(row.get("context_source") or ""),
                context_family=str(row.get("context_family") or ""),
                context_value=str(row.get("context_value") or ""),
                entry_weekday=str(row.get("entry_weekday") or ""),
                entry_weekday_num=int(row.get("entry_weekday_num")),
                entry_hour_utc=int(row.get("entry_hour_utc")),
                direction=direction,
                trades=int(float(row.get("trades", 0))),
                weeks=int(float(row.get("weeks", 0))),
                win_rate=float(row.get("win_rate", float("nan"))),
                avg_r=float(row.get("avg_r", float("nan"))),
                avg_r_ci_low=float(row.get("avg_r_ci_low", float("nan"))),
                avg_r_ci_high=None if pd.isna(row.get("avg_r_ci_high")) else float(row.get("avg_r_ci_high")),
                q_value_bh=None if pd.isna(row.get("q_value_bh")) else float(row.get("q_value_bh")),
            )
        )
    rules.sort(key=lambda rule: rule.score, reverse=True)
    log.info("Active weekday edge rules after filters: %d", len(rules))
    return rules


def fetch_klines(http: HTTP, symbol: str, interval: str, limit: int) -> pd.DataFrame:
    rows: dict[int, list[Any]] = {}
    end_ms: int | None = None
    bybit_interval = {"1h": "60", "1d": "D"}[interval]
    interval_ms = {"1h": 3_600_000, "1d": 86_400_000}[interval]
    while len(rows) < limit:
        kwargs: dict[str, Any] = {
            "category": CATEGORY,
            "symbol": symbol,
            "interval": bybit_interval,
            "limit": min(1000, max(1, limit - len(rows))),
        }
        if end_ms is not None:
            kwargs["end"] = end_ms
        response = http.get_kline(**kwargs)
        batch = response.get("result", {}).get("list", [])
        if not batch:
            break
        for item in batch:
            rows[int(item[0])] = item
        oldest = min(int(item[0]) for item in batch)
        end_ms = oldest - 1
        if len(batch) < kwargs["limit"]:
            break
        time.sleep(0.08)

    if not rows:
        raise RuntimeError(f"No klines returned for {symbol} {interval}")
    frame = pd.DataFrame(
        [rows[key] for key in sorted(rows)],
        columns=["open_time_ms", "open", "high", "low", "close", "volume", "turnover"],
    )
    frame["open_time"] = pd.to_datetime(frame["open_time_ms"].astype("int64"), unit="ms", utc=True)
    frame["close_time"] = frame["open_time"] + pd.Timedelta(milliseconds=interval_ms - 1)
    for column in ["open", "high", "low", "close", "volume", "turnover"]:
        frame[column] = pd.to_numeric(frame[column], errors="coerce").astype(float)
    now = pd.Timestamp.now(tz="UTC")
    frame = frame[frame["open_time"] + pd.Timedelta(milliseconds=interval_ms) <= now].copy()
    return frame[["open_time", "close_time", "open", "high", "low", "close", "volume", "turnover"]].dropna().reset_index(drop=True)


def rma(series: pd.Series, length: int) -> pd.Series:
    return series.ewm(alpha=1 / length, adjust=False, min_periods=length).mean()


def true_range(frame: pd.DataFrame) -> pd.Series:
    previous_close = frame["close"].shift(1)
    return pd.concat(
        [
            frame["high"] - frame["low"],
            (frame["high"] - previous_close).abs(),
            (frame["low"] - previous_close).abs(),
        ],
        axis=1,
    ).max(axis=1)


def rolling_last_percentile(series: pd.Series, window: int, min_periods: int) -> pd.Series:
    def percentile(values: np.ndarray) -> float:
        last = values[-1]
        clean = values[np.isfinite(values)]
        if clean.size == 0 or not np.isfinite(last):
            return np.nan
        return float(np.mean(clean <= last))

    return series.rolling(window, min_periods=min_periods).apply(percentile, raw=True)


def add_daily_regime(frame: pd.DataFrame) -> pd.DataFrame:
    out = frame.sort_values("open_time").reset_index(drop=True).copy()
    tr = true_range(out)
    atr = rma(tr, 14)
    up_move = out["high"].diff()
    down_move = -out["low"].diff()
    plus_dm = pd.Series(np.where((up_move > down_move) & (up_move > 0), up_move, 0.0), index=out.index)
    minus_dm = pd.Series(np.where((down_move > up_move) & (down_move > 0), down_move, 0.0), index=out.index)
    plus_di = 100.0 * rma(plus_dm, 14) / atr.replace(0, np.nan)
    minus_di = 100.0 * rma(minus_dm, 14) / atr.replace(0, np.nan)
    dx = 100.0 * (plus_di - minus_di).abs() / (plus_di + minus_di).replace(0, np.nan)
    adx = rma(dx, 14)
    out["atr_14"] = atr
    out["adx_14"] = adx
    out["ema_50"] = out["close"].ewm(span=50, adjust=False, min_periods=50).mean()
    out["ema_200"] = out["close"].ewm(span=200, adjust=False, min_periods=200).mean()
    out["ema_50_slope_10d"] = out["ema_50"].pct_change(10)
    mid = out["close"].rolling(20, min_periods=20).mean()
    stdev = out["close"].rolling(20, min_periods=20).std(ddof=0)
    out["bb_width"] = (4.0 * stdev) / mid.replace(0, np.nan)
    out["bb_width_pctile_100d"] = rolling_last_percentile(out["bb_width"], 100, 30)
    out["atr_pctile_100d"] = rolling_last_percentile(out["atr_14"], 100, 30)
    chop_len = 14
    tr_sum = tr.rolling(chop_len, min_periods=chop_len).sum()
    high_max = out["high"].rolling(chop_len, min_periods=chop_len).max()
    low_min = out["low"].rolling(chop_len, min_periods=chop_len).min()
    out["chop_14"] = 100.0 * np.log10((tr_sum / (high_max - low_min).replace(0, np.nan)).replace(0, np.nan)) / math.log10(chop_len)

    long_trend = (
        (out["adx_14"] >= 22.0)
        & (out["close"] > out["ema_50"])
        & (out["ema_50"] > out["ema_200"])
        & (out["ema_50_slope_10d"] > 0)
    )
    short_trend = (
        (out["adx_14"] >= 22.0)
        & (out["close"] < out["ema_50"])
        & (out["ema_50"] < out["ema_200"])
        & (out["ema_50_slope_10d"] < 0)
    )
    sideways = (
        ~(long_trend | short_trend)
        & (out["adx_14"] <= 18.0)
        & (out["bb_width_pctile_100d"] <= 0.45)
        & (out["atr_pctile_100d"] <= 0.55)
        & (out["chop_14"] < 55.0)
    )
    out["regime"] = np.select(
        [long_trend, short_trend, sideways],
        ["long_trending", "short_trending", "sideways"],
        default="chop",
    )
    out["regime_available_time"] = out["open_time"] + pd.Timedelta(days=1)
    return out


def hourly_atr(frame: pd.DataFrame, length: int) -> float:
    ordered = frame.sort_values("open_time").reset_index(drop=True)
    values = rma(true_range(ordered), length)
    return float(values.iloc[-1])


def monday_week_start(ts: pd.Timestamp) -> pd.Timestamp:
    return ts.floor("D") - pd.Timedelta(days=int(ts.weekday()))


def first_touch_time(frame: pd.DataFrame, column: str, value: float) -> pd.Timestamp:
    matches = frame[np.isclose(frame[column].astype(float), float(value), rtol=0.0, atol=1e-9)]
    if matches.empty:
        idx = frame[column].astype(float).idxmax() if column == "high" else frame[column].astype(float).idxmin()
        return utc_ts(frame.loc[idx, "open_time"])
    return utc_ts(matches["open_time"].iloc[0])


class MarketState:
    def __init__(self, public_http: HTTP) -> None:
        self.public_http = public_http
        self.hourly = pd.DataFrame()
        self.daily = pd.DataFrame()
        self.daily_regime = pd.DataFrame()
        self.lock = threading.Lock()

    def warmup(self) -> None:
        log.info("Fetching warmup candles for %s", SYMBOL)
        hourly = fetch_klines(self.public_http, SYMBOL, "1h", HOURLY_WARMUP_BARS)
        daily = fetch_klines(self.public_http, SYMBOL, "1d", DAILY_WARMUP_BARS)
        with self.lock:
            self.hourly = hourly
            self.daily = daily
            self.daily_regime = add_daily_regime(daily)
        log.info("Warmup complete: hourly=%d daily=%d", len(hourly), len(daily))

    def append_hourly(self, candle: dict[str, Any]) -> None:
        open_time = pd.to_datetime(int(candle["start"]), unit="ms", utc=True)
        row = {
            "open_time": open_time,
            "close_time": open_time + pd.Timedelta(milliseconds=3_600_000 - 1),
            "open": float(candle["open"]),
            "high": float(candle["high"]),
            "low": float(candle["low"]),
            "close": float(candle["close"]),
            "volume": float(candle.get("volume", 0.0)),
            "turnover": float(candle.get("turnover", 0.0) or 0.0),
        }
        with self.lock:
            self.hourly = pd.concat([self.hourly, pd.DataFrame([row])], ignore_index=True)
            self.hourly = self.hourly.drop_duplicates(subset=["open_time"], keep="last").sort_values("open_time").tail(max(HOURLY_WARMUP_BARS, 1000)).reset_index(drop=True)
            entry_time = open_time + pd.Timedelta(hours=1)
            if entry_time.hour == 0:
                self._update_completed_daily_from_hourly(entry_time - pd.Timedelta(days=1))

    def _update_completed_daily_from_hourly(self, day_start: pd.Timestamp) -> None:
        day_start = day_start.floor("D")
        day_end = day_start + pd.Timedelta(days=1)
        hours = self.hourly[(self.hourly["open_time"] >= day_start) & (self.hourly["open_time"] < day_end)].sort_values("open_time")
        if len(hours) < 20:
            return
        row = {
            "open_time": day_start,
            "close_time": day_end - pd.Timedelta(milliseconds=1),
            "open": float(hours["open"].iloc[0]),
            "high": float(hours["high"].max()),
            "low": float(hours["low"].min()),
            "close": float(hours["close"].iloc[-1]),
            "volume": float(hours["volume"].sum()),
            "turnover": float(hours["turnover"].sum()),
        }
        self.daily = pd.concat([self.daily, pd.DataFrame([row])], ignore_index=True)
        self.daily = self.daily.drop_duplicates(subset=["open_time"], keep="last").sort_values("open_time").tail(max(DAILY_WARMUP_BARS, 400)).reset_index(drop=True)
        self.daily_regime = add_daily_regime(self.daily)
        log.info("Updated completed daily candle for %s", day_start.date())

    def snapshot(self) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
        with self.lock:
            return self.hourly.copy(), self.daily.copy(), self.daily_regime.copy()

    def context_for_entry(self, entry_time: pd.Timestamp, entry_price: float) -> dict[str, str]:
        hourly, daily, daily_regime = self.snapshot()
        contexts: dict[str, str] = {"all": "all"}
        available_regimes = daily_regime[daily_regime["regime_available_time"] <= entry_time].dropna(subset=["regime"])
        if not available_regimes.empty:
            regime = str(available_regimes.iloc[-1]["regime"])
            contexts["daily_regime"] = regime

        week_start = monday_week_start(entry_time)
        monday_open_time = week_start
        monday_close_time = week_start + pd.Timedelta(days=1)
        if not (monday_close_time <= entry_time < week_start + pd.Timedelta(days=7)):
            return contexts

        monday_rows = daily[daily["open_time"] == monday_open_time]
        if monday_rows.empty:
            return contexts
        monday = monday_rows.iloc[-1]
        previous_week = daily[(daily["open_time"] >= week_start - pd.Timedelta(days=7)) & (daily["open_time"] < week_start)]
        previous_high = float(previous_week["high"].max()) if not previous_week.empty else float("nan")
        previous_low = float(previous_week["low"].min()) if not previous_week.empty else float("nan")

        monday_hours = hourly[(hourly["open_time"] >= monday_open_time) & (hourly["open_time"] < monday_close_time)].sort_values("open_time")
        if not monday_hours.empty:
            high_time = first_touch_time(monday_hours, "high", float(monday["high"]))
            low_time = first_touch_time(monday_hours, "low", float(monday["low"]))
            if high_time < low_time:
                sequence = "high_first"
            elif low_time < high_time:
                sequence = "low_first"
            else:
                sequence = "same_hour"
            contexts["monday_high_low_sequence"] = sequence

        monday_color = "doji"
        if float(monday["close"]) > float(monday["open"]):
            monday_color = "green"
        elif float(monday["close"]) < float(monday["open"]):
            monday_color = "red"
        contexts["monday_color"] = monday_color

        close_vs = "inside_previous_week_range"
        if np.isfinite(previous_high) and float(monday["close"]) > previous_high:
            close_vs = "above_pwh"
        elif np.isfinite(previous_low) and float(monday["close"]) < previous_low:
            close_vs = "below_pwl"
        contexts["monday_close_vs_pwh_pwl"] = close_vs

        if entry_price > float(monday["high"]):
            range_label = "above_monday_high"
        elif entry_price < float(monday["low"]):
            range_label = "below_monday_low"
        else:
            range_label = "inside_monday_range"
        contexts["entry_vs_monday_range"] = range_label
        contexts["entry_vs_monday_open"] = "above_or_at_monday_open" if entry_price >= float(monday["open"]) else "below_monday_open"
        monday_mid = (float(monday["high"]) + float(monday["low"])) / 2.0
        contexts["entry_vs_monday_mid"] = "above_or_at_monday_mid" if entry_price >= monday_mid else "below_monday_mid"

        if "daily_regime" in contexts:
            contexts["monday_color_x_daily_regime"] = f"{monday_color}|{contexts['daily_regime']}"
            contexts["entry_vs_monday_range_x_daily_regime"] = f"{range_label}|{contexts['daily_regime']}"
            contexts["monday_close_vs_pwh_pwl_x_daily_regime"] = f"{close_vs}|{contexts['daily_regime']}"
        return contexts


class FixedRiskExecutor:
    def __init__(self) -> None:
        self.http: HTTP | None = None
        self.info_cache: dict[str, dict[str, Any]] = {}
        self.leverage_synced: set[str] = set()
        if TRADING_ENABLED:
            if not API_KEY or not API_SECRET:
                raise RuntimeError("WEEKDAY_EDGE_TRADING_ENABLED=true requires WEEKDAY_EDGE_BYBIT_API_KEY/SECRET")
            self.http = HTTP(testnet=False, demo=TRADING_DEMO, api_key=API_KEY, api_secret=API_SECRET)

    def _info(self, symbol: str) -> dict[str, Any]:
        if self.http is None:
            raise RuntimeError("Trading HTTP client is disabled")
        if symbol not in self.info_cache:
            response = self.http.get_instruments_info(category=CATEGORY, symbol=symbol)
            items = response.get("result", {}).get("list", [])
            if not items:
                raise RuntimeError(f"No instrument info for {symbol}")
            item = items[0]
            lot = item.get("lotSizeFilter", {})
            price = item.get("priceFilter", {})
            lev = item.get("leverageFilter", {})
            self.info_cache[symbol] = {
                "status": str(item.get("status", "")),
                "qty_step": float(lot.get("qtyStep", "0.001")),
                "min_qty": float(lot.get("minOrderQty", "0.001")),
                "tick_size": float(price.get("tickSize", "0.01")),
                "max_leverage": float(lev.get("maxLeverage", "1") or "1"),
            }
        return self.info_cache[symbol]

    def _balance(self) -> dict[str, float]:
        if self.http is None:
            return {"equity": 0.0, "available": 0.0}
        response = self.http.get_wallet_balance(accountType="UNIFIED")
        row = response.get("result", {}).get("list", [{}])[0]
        total_equity = float(row.get("totalEquity", 0) or 0)
        total_available = float(row.get("totalAvailableBalance", 0) or 0)
        usdt_equity = 0.0
        usdt_available = 0.0
        for coin in row.get("coin", []):
            if coin.get("coin") != "USDT":
                continue
            usdt_equity = float(coin.get("equity", 0) or 0)
            usdt_available = float(coin.get("availableToWithdraw") or coin.get("availableToBorrow") or 0)
            break
        available = min(usdt_available, total_available) if usdt_available > 0 and total_available > 0 else (usdt_available or total_available)
        return {"equity": usdt_equity or total_equity, "available": available}

    def _has_open_position(self, symbol: str) -> bool:
        if self.http is None:
            return False
        response = self.http.get_positions(category=CATEGORY, symbol=symbol)
        for row in response.get("result", {}).get("list", []):
            try:
                if abs(float(row.get("size", 0) or 0)) > 0:
                    return True
            except Exception:
                continue
        return False

    def _ensure_leverage(self, symbol: str, max_leverage: float) -> None:
        if self.http is None or symbol in self.leverage_synced:
            return
        leverage_text = qty_to_str(max_leverage)
        try:
            response = self.http.set_leverage(
                category=CATEGORY,
                symbol=symbol,
                buyLeverage=leverage_text,
                sellLeverage=leverage_text,
            )
            if response.get("retCode", 0) != 0 and "not modified" not in str(response.get("retMsg", "")).lower():
                log.warning("set_leverage retCode=%s retMsg=%s", response.get("retCode"), response.get("retMsg"))
        except Exception as exc:
            if "leverage not modified" not in str(exc).lower():
                log.warning("set_leverage failed: %s", exc)
        self.leverage_synced.add(symbol)

    @staticmethod
    def _order_link_id(symbol: str, direction: str) -> str:
        ts = datetime.now(timezone.utc).strftime("%m%d%H%M")
        side = "L" if direction == "long" else "S"
        base = symbol.replace("USDT", "")[:8]
        return f"WE-{base}-{side}-{ts}-{uuid.uuid4().hex[:6].upper()}"[:36]

    def execute(self, signal_data: dict[str, Any]) -> dict[str, Any]:
        if not TRADING_ENABLED:
            return {"ok": False, "skipped": True, "message": "WEEKDAY_EDGE_TRADING_ENABLED=false"}
        if self.http is None:
            return {"ok": False, "message": "Trading HTTP client is not initialized"}

        symbol = str(signal_data["symbol"])
        direction = str(signal_data["direction"]).lower()
        entry = float(signal_data["entry"])
        stop = float(signal_data["stop"])
        target = float(signal_data["target"])
        unit_risk = abs(entry - stop)
        if unit_risk <= 0 or entry <= 0:
            return {"ok": False, "message": "Invalid entry/stop"}
        if unit_risk / entry < MIN_STOP_DISTANCE_PCT:
            return {"ok": False, "message": f"Stop distance {unit_risk / entry:.4%} below minimum"}

        fee_risk_per_unit = max(TAKER_FEE_RATE, 0.0) * (entry + stop)
        fee_to_price_risk = fee_risk_per_unit / unit_risk
        if MAX_FEE_TO_PRICE_RISK > 0 and fee_to_price_risk > MAX_FEE_TO_PRICE_RISK:
            return {"ok": False, "message": f"Fee/risk ratio {fee_to_price_risk:.2%} above limit"}

        if ONE_POSITION_ONLY and self._has_open_position(symbol):
            return {"ok": False, "skipped": True, "message": f"Open {symbol} position already exists"}

        info = self._info(symbol)
        if info.get("status") and info["status"] != "Trading":
            return {"ok": False, "message": f"{symbol} status={info['status']}"}
        balances = self._balance()
        equity = float(balances.get("equity", 0.0))
        available = float(balances.get("available", 0.0))
        if equity <= 0:
            return {"ok": False, "message": f"Invalid equity {equity}"}

        max_leverage = max(float(info.get("max_leverage", 1.0)), 1.0)
        q_step = float(info["qty_step"])
        min_qty = float(info["min_qty"])
        tick = float(info["tick_size"])
        unit_risk_for_sizing = unit_risk + fee_risk_per_unit if INCLUDE_FEES_IN_RISK else unit_risk
        raw_qty = RISK_USDT / unit_risk_for_sizing
        margin_basis = available if available > 0 else equity
        max_qty_by_margin = (margin_basis * max_leverage * 0.95) / entry
        qty_capped = False
        if raw_qty > max_qty_by_margin:
            raw_qty = max_qty_by_margin
            qty_capped = True
        qty = floor_to_step(raw_qty, q_step)
        if qty < min_qty:
            if not ALLOW_MIN_QTY_OVERRISK:
                return {
                    "ok": False,
                    "message": f"Risk too small for min qty: qty={qty_to_str(qty, q_step)} min={qty_to_str(min_qty, q_step)}",
                }
            qty = min_qty

        self._ensure_leverage(symbol, max_leverage)
        sl_price = round_to_step(stop, tick)
        tp_price = round_to_step(target, tick)
        side = "Buy" if direction == "long" else "Sell"
        link_id = self._order_link_id(symbol, direction)
        order: dict[str, Any] = {
            "category": CATEGORY,
            "symbol": symbol,
            "side": side,
            "orderType": "Market",
            "qty": qty_to_str(qty, q_step),
            "takeProfit": str(tp_price),
            "stopLoss": str(sl_price),
            "tpslMode": "Full",
            "tpTriggerBy": "LastPrice",
            "slTriggerBy": "LastPrice",
            "positionIdx": 0,
            "orderLinkId": link_id,
        }
        try:
            response = self.http.place_order(**order)
        except Exception as exc:
            exc_text = str(exc).lower()
            if "position idx" in exc_text or ("10001" in exc_text and "position" in exc_text):
                order["positionIdx"] = 1 if direction == "long" else 2
                order["orderLinkId"] = self._order_link_id(symbol, direction)
                try:
                    response = self.http.place_order(**order)
                except Exception as retry_exc:
                    return {"ok": False, "message": f"API exception after hedge retry: {retry_exc}"}
            else:
                return {"ok": False, "message": f"API exception: {exc}"}

        ret_code = int(response.get("retCode", -1))
        if ret_code == 10001 and "position idx" in str(response.get("retMsg", "")).lower():
            order["positionIdx"] = 1 if direction == "long" else 2
            order["orderLinkId"] = self._order_link_id(symbol, direction)
            try:
                response = self.http.place_order(**order)
                ret_code = int(response.get("retCode", -1))
            except Exception as retry_exc:
                return {"ok": False, "message": f"API exception after hedge retry: {retry_exc}"}
        if ret_code != 0:
            return {"ok": False, "message": f"Order rejected: {response.get('retCode')} {response.get('retMsg')}"}
        order_id = str(response.get("result", {}).get("orderId") or "")
        expected_price_risk = qty * unit_risk
        expected_fee_risk = qty * fee_risk_per_unit
        return {
            "ok": True,
            "order_id": order_id,
            "order_link_id": order.get("orderLinkId"),
            "qty": qty_to_str(qty, q_step),
            "qty_float": qty,
            "notional": qty * entry,
            "expected_price_risk": expected_price_risk,
            "expected_fee_risk": expected_fee_risk,
            "expected_total_risk": expected_price_risk + expected_fee_risk,
            "qty_capped_by_margin": qty_capped,
        }


class WeekdayEdgeBot:
    def __init__(self) -> None:
        self.public_http = HTTP(testnet=False, demo=False)
        self.market = MarketState(self.public_http)
        self.rules = load_rules(STATS_PATH)
        self.telegram = TelegramNotifier(TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID)
        self.executor = FixedRiskExecutor()
        self.rl = RlSidecarClient(RL_EXECUTION_URL, RL_EXECUTION_TIMEOUT_SECONDS, RL_EXECUTION_QUEUE_SIZE)
        self.normal_context = NormalRlContextBuilder(self.public_http)
        self.stop_event = threading.Event()
        self.ws: WebSocket | None = None
        self.last_ws_message_ts = time.time()
        self.last_heartbeat_ts = 0.0
        self.processed_entries: set[str] = set()
        self.ledger_lock = threading.Lock()

    def start(self) -> None:
        self.market.warmup()
        self._send_startup()
        self._open_ws()
        while not self.stop_event.is_set():
            now = time.time()
            if HEARTBEAT_SECONDS > 0 and now - self.last_heartbeat_ts >= HEARTBEAT_SECONDS:
                log.info("Heartbeat: waiting for %s closed 1h klines; active rules=%d", SYMBOL, len(self.rules))
                self.last_heartbeat_ts = now
            if WS_STALE_SECONDS > 0 and now - self.last_ws_message_ts > WS_STALE_SECONDS:
                raise SystemExit(f"No Bybit public WS message for {WS_STALE_SECONDS}s")
            time.sleep(1)

    def _open_ws(self) -> None:
        log.info("Opening Bybit public kline websocket symbol=%s demo=%s", SYMBOL, PUBLIC_WS_DEMO)
        self.ws = WebSocket(testnet=False, channel_type="linear", demo=PUBLIC_WS_DEMO)
        self.ws.kline_stream(interval=60, symbol=SYMBOL, callback=self._on_kline)

    def _send_startup(self) -> None:
        mode = "EXECUTION ON" if TRADING_ENABLED else "signal only"
        self.telegram.send(
            [
                "<b>[WEEKDAY EDGE] bot started</b>",
                f"Symbol: <code>{escape(SYMBOL)}</code>",
                f"Mode: <code>{escape(mode)}</code>",
                f"RL sidecar: <code>{'on' if RL_EXECUTION_URL else 'off'}</code>",
                f"Risk: <code>{fmt(RISK_USDT, 2)} USDT</code>  RR: <code>{fmt(RR, 2)}</code>  SL: <code>{fmt(SL_ATR_MULTIPLE, 2)}x ATR{ATR_LENGTH}</code>",
                f"Rules: <code>{len(self.rules)}</code>",
            ]
        )

    def _on_kline(self, msg: dict[str, Any]) -> None:
        self.last_ws_message_ts = time.time()
        try:
            data = msg.get("data") or []
            if not data:
                return
            candle = data[0]
            if not candle.get("confirm", False):
                return
            self.market.append_hourly(candle)
            open_time = pd.to_datetime(int(candle["start"]), unit="ms", utc=True)
            entry_time = open_time + pd.Timedelta(hours=1)
            key = f"{SYMBOL}:{entry_time.isoformat()}"
            if key in self.processed_entries:
                return
            self.processed_entries.add(key)
            if len(self.processed_entries) > 500:
                self.processed_entries = set(sorted(self.processed_entries)[-250:])
            self._evaluate_closed_hour(entry_time, float(candle["close"]))
        except Exception:
            log.exception("Error in kline callback")

    def _evaluate_closed_hour(self, entry_time: pd.Timestamp, entry_price: float) -> None:
        hourly, _, _ = self.market.snapshot()
        if len(hourly) < ATR_LENGTH + 5:
            return
        atr = hourly_atr(hourly, ATR_LENGTH)
        if not np.isfinite(atr) or atr <= 0:
            return
        weekday_num = int(entry_time.weekday())
        hour = int(entry_time.hour)
        contexts = self.market.context_for_entry(entry_time, entry_price)
        matches = self._matching_rules(weekday_num, hour, contexts)
        if not matches:
            log.info("No rule match at %s close=%.2f contexts=%s", entry_time.isoformat(), entry_price, contexts)
            return

        selected = matches[0]
        direction = selected.direction
        risk = atr * SL_ATR_MULTIPLE
        if direction == "long":
            stop = entry_price - risk
            target = entry_price + risk * RR
        else:
            stop = entry_price + risk
            target = entry_price - risk * RR
        signal_data = {
            "event_id": uuid.uuid4().hex,
            "symbol": SYMBOL,
            "strategy": STRATEGY_NAME,
            "entry_time": entry_time.isoformat(),
            "entry": entry_price,
            "stop": stop,
            "target": target,
            "risk": risk,
            "atr": atr,
            "direction": direction,
            "rule": selected.__dict__,
            "contexts": contexts,
            "matched_rules": [rule.__dict__ for rule in matches[:MAX_MATCHES_IN_MESSAGE]],
        }
        self._attach_normal_rl_context(signal_data, hourly, contexts)
        try:
            execution = self.executor.execute(signal_data)
        except Exception as exc:
            log.exception("Execution failed; sending signal without order")
            execution = {"ok": False, "message": f"Execution error: {exc}"}
        signal_data["execution"] = execution
        signal_data["rl_dispatch"] = self.rl.enqueue(self._build_rl_signal_payload(signal_data))
        self._write_ledger(signal_data)
        self._send_signal(signal_data, matches)
        log.info(
            "Signal %s %s entry=%.2f sl=%.2f tp=%.2f rule=%s execution=%s",
            SYMBOL,
            direction,
            entry_price,
            stop,
            target,
            selected.label,
            execution.get("message") or execution.get("order_id") or execution.get("ok"),
        )

    def _attach_normal_rl_context(self, signal_data: dict[str, Any], hourly: pd.DataFrame, contexts: dict[str, str]) -> None:
        try:
            feature_snapshot = self.normal_context.normal_feature_snapshot(hourly, str(signal_data.get("direction") or ""))
            signal_data["feature_snapshot"] = feature_snapshot
            signal_data["feature_columns"] = list(feature_snapshot.keys()) or list(FEATURE_NAMES)
        except Exception as exc:
            log.debug("Normal RL feature snapshot failed: %s", exc)
            signal_data["feature_snapshot"] = {}
            signal_data["feature_columns"] = list(FEATURE_NAMES)
        try:
            market_context = self.normal_context.build(signal_data, hourly, contexts)
            signal_data["market_context"] = market_context
            signal_data["market_snapshot"] = market_context.get("ticker") if isinstance(market_context, dict) else {}
        except Exception as exc:
            log.warning("Normal RL market context failed: %s", exc)
            signal_data["market_context"] = {}
            signal_data["market_snapshot"] = {}

    def _build_rl_signal_payload(self, signal_data: dict[str, Any]) -> dict[str, Any]:
        rule = signal_data["rule"]
        entry = float(signal_data["entry"])
        stop = float(signal_data["stop"])
        target = float(signal_data["target"])
        risk = abs(entry - stop)
        historic_probability = finite_float(rule.get("win_rate"))
        if historic_probability is None:
            historic_probability = RL_PROBABILITY
        feature_snapshot = signal_data.get("feature_snapshot") if isinstance(signal_data.get("feature_snapshot"), dict) else {}
        features: dict[str, Any] = dict(feature_snapshot)
        features.update(
            {
                "ml_probability": historic_probability,
                "ml_threshold": RL_THRESHOLD,
                "normal_bot_status_accepted": 1.0,
                "normal_bot_status_rejected": 0.0,
            }
        )

        execution = signal_data.get("execution") if isinstance(signal_data.get("execution"), dict) else {}
        market_context = signal_data.get("market_context") if isinstance(signal_data.get("market_context"), dict) else {}
        market_snapshot = signal_data.get("market_snapshot") if isinstance(signal_data.get("market_snapshot"), dict) else {}
        return jsonable(
            {
                "schema_version": "rl_signal_v1",
                "event_id": signal_data.get("event_id") or uuid.uuid4().hex,
                "source": "weekday-edge-bot",
                "sent_at": datetime.now(timezone.utc).isoformat(),
                "status": "accepted",
                "reason": None,
                "symbol": signal_data.get("symbol"),
                "strategy": STRATEGY_NAME,
                "direction": signal_data.get("direction"),
                "setup": {
                    "entry": entry,
                    "stop_loss": stop,
                    "take_profit": target,
                    "trail_dist": None,
                    "exit_style": "fixed_tp",
                    "entry_time": signal_data.get("entry_time"),
                    "atr": signal_data.get("atr"),
                    "stop_distance_pct": risk / entry if entry > 0 else None,
                    "fee_to_price_risk": (
                        max(TAKER_FEE_RATE, 0.0) * (entry + stop) / risk
                        if risk > 0
                        else None
                    ),
                    "upstream_order_id": execution.get("order_id"),
                    "upstream_order_link_id": execution.get("order_link_id"),
                },
                "features": features,
                "feature_columns": list(signal_data.get("feature_columns") or features.keys()),
                "ml_probability": historic_probability,
                "ml_threshold": RL_THRESHOLD,
                "default_risk_usdt": RISK_USDT,
                "risk_config": {
                    "fixed_risk_usdt": RISK_USDT,
                    "min_stop_distance_pct": MIN_STOP_DISTANCE_PCT,
                    "taker_fee_rate": TAKER_FEE_RATE,
                    "max_fee_to_price_risk": MAX_FEE_TO_PRICE_RISK,
                    "sl_atr_multiple": SL_ATR_MULTIPLE,
                    "rr": RR,
                    "atr_length": ATR_LENGTH,
                },
                "market_context": market_context,
                "market_snapshot": market_snapshot,
                "raw_signal": signal_data,
                "extra": {
                    "direct_weekday_edge_execution": execution,
                    "weekday_edge_rule": rule,
                    "weekday_edge_contexts": signal_data.get("contexts"),
                    "historic_win_rate": rule.get("win_rate"),
                    "historic_avg_r": rule.get("avg_r"),
                },
            }
        )

    def _matching_rules(self, weekday_num: int, hour: int, contexts: dict[str, str]) -> list[Rule]:
        matches = [
            rule
            for rule in self.rules
            if rule.entry_weekday_num == weekday_num
            and rule.entry_hour_utc == hour
            and contexts.get(rule.context_family) == rule.context_value
        ]
        matches.sort(key=lambda rule: rule.score, reverse=True)
        return matches

    def _send_signal(self, signal_data: dict[str, Any], matches: list[Rule]) -> None:
        rule = matches[0]
        execution = signal_data["execution"]
        direction = str(signal_data["direction"]).upper()
        ci_high = "-" if rule.avg_r_ci_high is None else fmt(rule.avg_r_ci_high, 3)
        q_text = "-" if rule.q_value_bh is None else fmt(rule.q_value_bh, 3)
        lines = [
            "<b>[WEEKDAY EDGE] BTC 1R SIGNAL</b>",
            f"Time: <code>{escape(signal_data['entry_time'])}</code>",
            f"Direction: <b>{escape(direction)}</b>  Rule: <code>{escape(rule.label)}</code>",
            f"Entry: <code>{fmt_price(signal_data['entry'])}</code>",
            f"SL: <code>{fmt_price(signal_data['stop'])}</code>  TP: <code>{fmt_price(signal_data['target'])}</code>",
            f"Risk distance: <code>{fmt_price(signal_data['risk'])}</code>  ATR{ATR_LENGTH}: <code>{fmt_price(signal_data['atr'])}</code>",
            f"Stats: WR <code>{rule.win_rate * 100:.1f}%</code>  avgR <code>{rule.avg_r:+.3f}</code>  CI <code>[{rule.avg_r_ci_low:+.3f}, {ci_high}]</code>",
            f"Sample: <code>{rule.trades}</code> trades / <code>{rule.weeks}</code> weeks  q <code>{q_text}</code>",
        ]
        if len(matches) > 1:
            other = ", ".join(f"{r.context_family}={r.context_value}:{r.direction}:{r.avg_r:+.2f}R" for r in matches[1:MAX_MATCHES_IN_MESSAGE])
            lines.append(f"Also matched: <code>{escape(other)}</code>")
        if execution.get("ok"):
            lines.append(
                "Demo order: "
                f"<b>placed</b> qty <code>{escape(str(execution.get('qty')))}</code> "
                f"risk~<code>{fmt(float(execution.get('expected_total_risk', 0.0)), 2)} USDT</code> "
                f"id <code>{escape(str(execution.get('order_id')))}</code>"
            )
        else:
            status = "skipped" if execution.get("skipped") else "not placed"
            lines.append(f"Demo order: <b>{escape(status)}</b> - <code>{escape(str(execution.get('message', '-')))}</code>")
        rl_dispatch = signal_data.get("rl_dispatch") if isinstance(signal_data.get("rl_dispatch"), dict) else {}
        if rl_dispatch.get("enabled"):
            rl_status = "queued" if rl_dispatch.get("queued") else "not queued"
            lines.append(f"RL sidecar: <b>{escape(rl_status)}</b>")
        self.telegram.send(lines)

    def _write_ledger(self, payload: dict[str, Any]) -> None:
        LEDGER_PATH.parent.mkdir(parents=True, exist_ok=True)
        with self.ledger_lock:
            with LEDGER_PATH.open("a", encoding="utf-8") as handle:
                handle.write(json.dumps(payload, default=str, separators=(",", ":")) + "\n")

    def stop(self) -> None:
        self.stop_event.set()
        try:
            if self.ws is not None:
                self.ws.exit()
        except Exception:
            pass


def main() -> None:
    bot = WeekdayEdgeBot()

    def handle_signal(signum: int, _frame: Any) -> None:
        log.info("Received signal %s; stopping", signum)
        bot.stop()

    signal.signal(signal.SIGTERM, handle_signal)
    signal.signal(signal.SIGINT, handle_signal)
    bot.start()


if __name__ == "__main__":
    main()
